# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

user = User.create!(email: "user1991@gmail.com", password: "password")

Dream.create(date: "2015-01-02", text: "My dream has two main sections and is very long. It begins at a different version of our older home on Stadcor Street in Wavell Heights. However, our house is built directly over the ground (instead of up on stumps) and has a dirt floor, which does not trigger the fact that I am dreaming. I notice a large garden in our living room growing directly from the \"floor\". They are large-leafed vine-like plants; possibly cantaloupes. Over time, however, I want to make our house more like a modern home and have our garden outside. It seems somewhat frustrating to me though I do notice sheets of vinyl and carpet over some areas of the dirt floor in different rooms, but only covering about half the area. This combination of vinyl or carpet over a dirt floor seems more aggravating than just having a dirt floor throughout.
        Zsuzsanna comes in and tells me that she is going to visit an older lady that she knew when she was younger. Before visiting her, she decides to become fifteen years old again so there will not be any confusion as to who she is, as the older lady will recognize her more easily. This does not at all seem unusual to me but I start to worry about her as she leaves on her bicycle - the one she apparently had at that time when she knew this person - and \"calls it into existence\" as such again. Instead of this scene triggering lucidity, I instead eventually decide that I will catch up to her to make sure she stays safe. Of course, to do this, I take to the air to fly (still not becoming lucid).
        I fly over what seems like a resort near a beach, but there is also an urban area. Flying down and around the people does not surprise them that much. In fact, one shirtless chubby male in swimming trunks waves at me from a lawn chair. I do have to dodge a few power lines. I also briefly see Zsa Zsa Gabor (very old) who regards me without emotion.
        I fly in a semicircular path and land in an industrial area near a fence and see my wife approaching on her bicycle (which for a short time seems to be a three-wheeledrickshaw with packages on the seat to her right - however it is soon a bicycle again). She seems cheerful and okay as she soon hears me calling out her name (\"Suzi\") rather loudly. Three unknown people are there and I start randomly talking to them about others in the area as my wife approaches on bicycle. One unknown male claims they are my relatives and that the person I thought was Zsa Zsa Gabor may actually be an elderly lady I visited as a child whose surname (real-life as well) was Love. I am not sure if the surname he gives for himself is Toms or Thomas (though I do hear \"Toms\" at first, it seems).
        My wife is happy to see me and seems about twenty years old now. We decide to fly off together, but first, I must hide her bicycle so that no one steals it. I use telekinesis (still not lucid) and move it to near the sidewalk. From here, I transform the bicycle now lying on its side into a red fire hydrant which rises slowly from the ground as it forms and becomes harder and more uniform. My apparently fictional relatives gaze at the fire hydrant quite oddly as if they know I am deliberately being obnoxious to them by manifesting a metaphorical erection so boldly (albeit with supposed witchcraft).
        My wife and I fly around while holding each other close, though there are several annoying younger chubby males who seem to not like us being there and suspect us of being witches intent on destroying their town. We fly near a higher hill overlooking the town where there are other people entering a cave above a cliff. These people seem more intelligent and spiritual than the people below in the adjacent town but we do not converse with them.
        A few of the other males in the resort area soon somehow develop the ability to fly. This annoys me because they are now a threat. My wife and I move apart and run about in the air, about ten feet from the ground, to distract them from going in just one direction. Soon, the palm of my right hand grows a mouth with sharp shark-like teeth and my arm stretches several times its normal length to become an octopus tentacle reaching all the way to the ground. Any male that flies near either of us is grabbed and either \"eaten\" or thrown down hard enough to disintegrate them.
        I flip backwards in midair, my body arcing back as I hover above the town and I then mentally force a newly declared “truth” that no other person from this town will ever be able to fly. This works (in this particular dream) and I feel strongly that no one else will ever fly or be a threat at least when we are flying. \"Let\'s get away from this looney bin,\" I say to my wife.    My wife and I again hold each other in flight and we converse about how timeless and ageless our love has been and even make subtle in-jokes about our years of romance and bizarre experiences with humanity and their typically strange and limiting beliefs. It dawns on me yet again that I knew of her existence just before I was born (and even longer before she was born).
        In the back of my mind, I vaguely contemplate the earthquake that rattled our house in a sweeping wave a few hours before in real life. It seemed to move from the front room where I was, under my feet, continuing in a vibrating wave almost as if a large animal was moving underground northeast to southwest with moderate speed. I could actually feel the floorboards vibrating in sequence from the front to the back of the house as I heard it move through my oldest son\'s room in the same way - my first real earthquake. I was not aware they occurred like this; that is, as if traveling from one area to another like a wave, as I had always thought the ground shook in the same place for a time as in movies.", user: user)
Dream.create(date: "2015-03-02", text: "Lately, I have been having more uneventful dreams that mostly only represent the waking process, likely because I have written a bit more on it recently. This situation is probably number two in the most common waking metaphors, that being trying to find something in an empty grocery store (or a store that gets emptier over time), the first most common (for me) being lowering water and disappearing lakes and rivers (sometimes with less and less fish if I am fishing). Both of these dream-rendered waking metaphors are analogous with the passage of time and \"less access\" (to the other layers of mind and levels of consciousness). For example, a river may dry up over time, and a store may eventually sell everything in stock.

        My wife and I go into an unfamiliar grocery store, of which the entrance seems directly from the sidewalk and city streets. I am unsure of the town. Firstly, I am looking at jars of pickles that I contemplate buying for my wife. The lid somehow comes off one jar when I tip it to try to find the label (there does not seem to be one and I get the impression it is from an individual who sells wholesale to the store) and two pickles fall to the floor. I think about buying the jar out of a vague sense of \"responsibility\" to the store (as no one else would buy the jar if they knew), but instead put the pickles back and pretend that nothing happened. (I could write a page on this obvious symbolism alone, but I think I will pass this time.) Instead of a shelf, the large pickle jars, about five of them, are in a wooden display like in the vegetables section. Each pickle is about as high as the jar, about five to a jar, arranged vertically.
        A little later, I start pushing a shopping cart through the aisles of the store. A (unknown) girl who works there is standing in one aisle (the last aisle on one side of the store; the most distant from the entrance) and we talk for a short time as I then realize that instead of shelves, the sides of the aisle are actually random pieces of plywood (though all similar in size) nailed up everywhere - some yellowish, some white, one piece looking like it was borrowed from an old sign. Looking around, I do not see any shelves or areas with any food and become annoyed.
        My wife and I leave the store without buying anything. A few people, possibly homeless people, start following us. They are friendly but somewhat sickly looking. An older female (perhaps fifty), asks me if I can help her. For some reason, I put my hand near her forehead (not touching it), moving it about as if \"detecting\" anything that might be wrong with her. (I used to do this in real life years ago when someone said something preposterous - a gag on checking their temperature to see if they are okay.)
       She almost seems to faint though I push her back so that she does not fall in my direction. After a short time, I tell her that she needs more Vitamin A. I tell her that she needs to start eating a lot of tomatoes to become healthier and fix whatever problems she has. She seems very happy. An unknown friendly and cheerful male smiles at my ability to do this and then adds to the conversation by talking about lentils, which is what he thought I had been talking about. I am annoyed but decide not to correct him. From here, my wife and I go to a larger grocery store, but I begin to wake before doing much.", user: user)
Dream.create(date: "2015-12-14", text: "I am seemingly back in the living room in Cubitis, seated at a large wooden table in the southwest corner. My computer is set up in a similar way as with my desk in real life. (I still, after all these years, often do not catch on that I am dreaming when in such a setting.) My wife and children live here as well, it seems. At one point, our pet chicken is sitting on the table to the left of my computer keyboard. It seems to be an Araucana or Ameraucana hen. The sense of touch is enhanced. I feel weight and motion very vividly as I try to make sure the hen does not hurt herself by quickly jumping or flapping her wings. Our black and white cat (I assume Franco) eventually emerges from the hallway. He jumps up on the table and bites into the back of the hen. This greatly concerns me because I know he will probably kill it and I am horrified. I try to push him back and whack my hand over the animals, but the chicken is taken to the floor by the cat.

        I get the impression that I may have accidentally detached either the hen's head or the cat's, or possibly both are severely injured. I am not sure what to do, as our two pets may both be lost. I get the impression that a griffin may result, though possibly fairly weak until fed, as it is lying on its side, looking a bit fatigued.", user: user)
Dream.create(date: "2015-08-02", text: "I had a different style of dream than usual for one of my first scenes of wandering about but decide that ecstasy, for now, can wait. I \"jump\" into a mostly featureless area (which could be either inside or outside) and am frustrated with the nature of humanity, not angrily so, but in an \"I don\'t get it at all\" sense. An (unknown, presumably at the time) female entity is present but appears mostly only as blue lines of nerve networks - with the effect of \"walking blue lightning\" but maintaining human form. She tells me to \"make it go\", referring to spinning a very large pumpkin. I do this several times, from a few feet away (never touching it) and find it effortless but also boring. The pumpkin is very large. I suppose it is somewhat like a \"release\", just to focus all my thoughts to spin around this large pumpkin and see what happens. At times, it seems to change, but mostly remains a spinning pumpkin. At one point, I do get an impression of gears behind gears behind more gears, not really doing anything else, but just being cogs that turn other cogs, infinitely.

       \"This is really boring,\" I tell the entity. I had not created any dream scripts recently - or even foundations of such (well, since about two days ago anyway), so, on another level, I am just waiting to wake for this period, which is not really like me at all (typically anyway).

       I create a city bus scene, but she and I are the only ones on it. I become like blue nerve networks as well. We walk around on the bus - her from the back end seat and me on the left side in the middle of the bus, on a wider seat facing to the right, acting out \"first meetings\". I switch places with her several times \"leaping\" horizontally back and forth between our forms even as we are walking towards each other over different \"resets\". The setting is mostly dark, enhancing the glowing nerve-network-like forms. There is a sheen to our glass-like \"skin\", with sometimes a hint of gold in some sort of larger internal \"nerve\" or singular \"vein\". There is form and motion, but I feel like doing something else, though mostly my dream remains featureless and uneventful, yet relaxing. Being her and being me is very similar.", user: user)
Dream.create(date: "2015-09-25", text: "I am at an unknown library (in one of three dreams that was firstly set at a library). It seems to be an area without as much public access, though the room\'s perimeter is covered with shelves full of books (though they are the only shelves in the room). The people who are there, all seated around a large rectangular table, seem like a mix of old classmates, coworkers, and random fictional characters.

        At one point, when I am bored with regard to what one character is talking about, I hover in the air and grow bat wings. They look at me in a strange manner as if they are concerned. I notice that my wings look a bit sketchy, almost as if drawn quickly with a charcoal pencil. I still use them to fly around.

        One person starts gossiping about me because I am dressed in black and have bat\'s wings - so I wave my hand and I then have large white bird\'s wings instead and am dressed in mostly white. \"You can\'t label me, because I am everything that exists,\" I say. To augment my point, I dissolve my wings and then fly around without any wings, in various positions. The people seem wary and introverted at this point.", user: user)
Dream.create(date: "2015-01-02", text: "I seem to be fairly young again and living with my parents, though I do not feel that much like a child in my dream. I am not sure where we are living. It seems vaguely like the Stadcor Street house where my wife Zsuzsanna and I lived years ago with our two oldest children. My mother is also present and is concerned about my father.

        My father (deceased February 14, 1979) is home early from his work in construction. He has his shirt off and is in pain because of a large creature wrapped around his abdomen as well as being partly inside his stomach. Apparently it is some sort of very large tapeworm or parasite but actually looks like a sea snake. It is wrapped around at least three times in horizontal layers and there is a section that goes inside his abdomen. He sits on the bed and seems in distress. He appears as he did perhaps in 1960 (or even the late 1950s before I was born).

        I start to contemplate why he waited so long to consider having it removed. Now it would be more difficult than ever to have it removed due to its large size. I think about how they would have to put the creature to sleep before removing all of it. The imagery is very clear and continues for at least (seemingly) fifteen minutes. It does not seem it will be fatal, though does seem quite odd to put up with such a problem. I think about how my father could have gotten around and done his work with that creature there all the time. Apparently, it has only started to worsen recently, as it has gotten bigger.

       At one point, the creature\'s head seems to be disconnected but is somehow still alive and clamped on, though I still get the impression that it will soon die from having its head detached.", user: user)
