# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

user = User.create(email: "user@gmail.com", password: "password")

Dream.create(user: user, date: Date.today, text: "My dream has two main sections and is very long. It begins at a different version of our older home on Stadcor Street in Wavell Heights. However, our house is built directly over the ground (instead of up on stumps) and has a dirt floor, which does not trigger the fact that I am dreaming. I notice a large garden in our living room growing directly from the \"floor\". They are large-leafed vine-like plants; possibly cantaloupes. Over time, however, I want to make our house more like a modern home and have our garden outside. It seems somewhat frustrating to me though I do notice sheets of vinyl and carpet over some areas of the dirt floor in different rooms, but only covering about half the area. This combination of vinyl or carpet over a dirt floor seems more aggravating than just having a dirt floor throughout.
        Zsuzsanna comes in and tells me that she is going to visit an older lady that she knew when she was younger. Before visiting her, she decides to become fifteen years old again so there will not be any confusion as to who she is, as the older lady will recognize her more easily. This does not at all seem unusual to me but I start to worry about her as she leaves on her bicycle - the one she apparently had at that time when she knew this person - and \"calls it into existence\" as such again. Instead of this scene triggering lucidity, I instead eventually decide that I will catch up to her to make sure she stays safe. Of course, to do this, I take to the air to fly (still not becoming lucid).
        I fly over what seems like a resort near a beach, but there is also an urban area. Flying down and around the people does not surprise them that much. In fact, one shirtless chubby male in swimming trunks waves at me from a lawn chair. I do have to dodge a few power lines. I also briefly see Zsa Zsa Gabor (very old) who regards me without emotion.")
Dream.create(user: user, date: "2015-10-13", text: "My wife and I go into an unfamiliar grocery store, of which the entrance seems directly from the sidewalk and city streets. I am unsure of the town. Firstly, I am looking at jars of pickles that I contemplate buying for my wife. The lid somehow comes off one jar when I tip it to try to find the label (there does not seem to be one and I get the impression it is from an individual who sells wholesale to the store) and two pickles fall to the floor. I think about buying the jar out of a vague sense of \"responsibility\" to the store (as no one else would buy the jar if they knew), but instead put the pickles back and pretend that nothing happened. (I could write a page on this obvious symbolism alone, but I think I will pass this time.) Instead of a shelf, the large pickle jars, about five of them, are in a wooden display like in the vegetables section. Each pickle is about as high as the jar, about five to a jar, arranged vertically.
        A little later, I start pushing a shopping cart through the aisles of the store. A (unknown) girl who works there is standing in one aisle (the last aisle on one side of the store; the most distant from the entrance) and we talk for a short time as I then realize that instead of shelves, the sides of the aisle are actually random pieces of plywood (though all similar in size) nailed up everywhere - some yellowish, some white, one piece looking like it was borrowed from an old sign. Looking around, I do not see any shelves or areas with any food and become annoyed.")
Dream.create(user: user, date: "2015-10-14", text: "\"This is really boring,\" I tell the entity. I had not created any dream scripts recently - or even foundations of such (well, since about two days ago anyway), so, on another level, I am just waiting to wake for this period, which is not really like me at all (typically anyway).
       I create a city bus scene, but she and I are the only ones on it. I become like blue nerve networks as well. We walk around on the bus - her from the back end seat and me on the left side in the middle of the bus, on a wider seat facing to the right, acting out \"first meetings\". I switch places with her several times \"leaping\" horizontally back and forth between our forms even as we are walking towards each other over different \"resets\". The setting is mostly dark, enhancing the glowing nerve-network-like forms. There is a sheen to our glass-like \"skin\", with sometimes a hint of gold in some sort of larger internal \"nerve\" or singular \"vein\". There is form and motion, but I feel like doing something else, though mostly my dream remains featureless and uneventful, yet relaxing. Being her and being me is very similar.")
Dream.create(user: user, date: "2015-10-10", text: "At one point, when I am bored with regard to what one character is talking about, I hover in the air and grow bat wings. They look at me in a strange manner as if they are concerned. I notice that my wings look a bit sketchy, almost as if drawn quickly with a charcoal pencil. I still use them to fly around.")
Dream.create(user: user, date: "2015-10-20", text: "My father (deceased February 14, 1979) is home early from his work in construction. He has his shirt off and is in pain because of a large creature wrapped around his abdomen as well as being partly inside his stomach. Apparently it is some sort of very large tapeworm or parasite but actually looks like a sea snake. It is wrapped around at least three times in horizontal layers and there is a section that goes inside his abdomen. He sits on the bed and seems in distress. He appears as he did perhaps in 1960 (or even the late 1950s before I was born).")
Dream.create(user: user, date: "2015-10-03", text: "I start to contemplate why he waited so long to consider having it removed. Now it would be more difficult than ever to have it removed due to its large size. I think about how they would have to put the creature to sleep before removing all of it. The imagery is very clear and continues for at least (seemingly) fifteen minutes. It does not seem it will be fatal, though does seem quite odd to put up with such a problem. I think about how my father could have gotten around and done his work with that creature there all the time. Apparently, it has only started to worsen recently, as it has gotten bigger.")
Dream.create(user: user, date: "2015-09-13", text: "I had a different style of dream than usual for one of my first scenes of wandering about but decide that ecstasy, for now, can wait. I \"jump\" into a mostly featureless area (which could be either inside or outside) and am frustrated with the nature of humanity, not angrily so, but in an \"I don\'t get it at all\" sense. An (unknown, presumably at the time) female entity is present but appears mostly only as blue lines of nerve networks - with the effect of \"walking blue lightning\" but maintaining human form. She tells me to \"make it go\", referring to spinning a very large pumpkin. I do this several times, from a few feet away (never touching it) and find it effortless but also boring. The pumpkin is very large. I suppose it is somewhat like a \"release\", just to focus all my thoughts to spin around this large pumpkin and see what happens. At times, it seems to change, but mostly remains a spinning pumpkin. At one point, I do get an impression of gears behind gears behind more gears, not really doing anything else, but just being cogs that turn other cogs, infinitely.")
Dream.create(user: user, date: "2015-09-25", text: "My wife and I leave the store without buying anything. A few people, possibly homeless people, start following us. They are friendly but somewhat sickly looking. An older female (perhaps fifty), asks me if I can help her. For some reason, I put my hand near her forehead (not touching it), moving it about as if \"detecting\" anything that might be wrong with her. (I used to do this in real life years ago when someone said something preposterous - a gag on checking their temperature to see if they are okay. She almost seems to faint though I push her back so that she does not fall in my direction. After a short time, I tell her that she needs more Vitamin A. I tell her that she needs to start eating a lot of tomatoes to become healthier and fix whatever problems she has. She seems very happy. An unknown friendly and cheerful male smiles at my ability to do this and then adds to the conversation by talking about lentils, which is what he thought I had been talking about. I am annoyed but decide not to correct him. From here, my wife and I go to a larger grocery store, but I begin to wake before doing much.")
Dream.create(user: user, date: "2015-09-17", text: "Zsuzsanna comes in and tells me that she is going to visit an older lady that she knew when she was younger. Before visiting her, she decides to become fifteen years old again so there will not be any confusion as to who she is, as the older lady will recognize her more easily. This does not at all seem unusual to me but I start to worry about her as she leaves on her bicycle - the one she apparently had at that time when she knew this person - and \"calls it into existence\" as such again. Instead of this scene triggering lucidity, I instead eventually decide that I will catch up to her to make sure she stays safe. Of course, to do this, I take to the air to fly (still not becoming lucid).
        I fly over what seems like a resort near a beach, but there is also an urban area. Flying down and around the people does not surprise them that much. In fact, one shirtless chubby male in swimming trunks waves at me from a lawn chair. I do have to dodge a few power lines. I also briefly see Zsa Zsa Gabor (very old) who regards me without emotion.")
